#!/bin/bash
# Script to update Nginx CORS configuration for beta environment
# This script documents the commands that need to be run on the VPS server

echo "=== Nginx CORS Configuration Update for Beta Environment ==="
echo ""
echo "This script documents the steps needed to update the Nginx CORS configuration"
echo "on the VPS server to include the new beta Netlify origin."
echo ""

echo "Step 1: SSH to the VPS server"
echo "----------------------------------------"
echo "ssh root@185.193.126.13"
echo ""

echo "Step 2: Backup the current Nginx configuration"
echo "----------------------------------------"
echo "cp /etc/nginx/sites-available/api-beta.workforcedemocracyproject.org /etc/nginx/sites-available/api-beta.workforcedemocracyproject.org.backup"
echo ""

echo "Step 3: Edit the Nginx configuration file"
echo "----------------------------------------"
echo "nano /etc/nginx/sites-available/api-beta.workforcedemocracyproject.org"
echo ""
echo "Add or update the configuration with the following:"
echo ""
echo "# Add mapping for CORS origins"
echo "map \"\$http_origin\" \$cors_origin {"
echo "    default \"\";"
echo "    \"~^https://workforcedemocracyproject\\.org$\" \"https://workforcedemocracyproject.org\";"
echo "    \"~^https://www\\.workforcedemocracyproject\\.org$\" \"https://www.workforcedemocracyproject.org\";"
echo "    \"~^https://workforcedemocracyproject\\.netlify\\.app$\" \"https://workforcedemocracyproject.netlify.app\";"
echo "    \"~^https://beta-workforcedemocracyproject\\.netlify\\.app$\" \"https://beta-workforcedemocracyproject.netlify.app\";"
echo "    \"http://localhost:3000\" \"http://localhost:3000\";"
echo "    \"http://127.0.0.1:3000\" \"http://127.0.0.1:3000\";"
echo "}"
echo ""
echo "# In the location block, update CORS headers"
echo "location / {"
echo "    # ... existing proxy settings ..."
echo ""
echo "    # CORS Headers"
echo "    add_header 'Access-Control-Allow-Origin' \$cors_origin always;"
echo "    add_header 'Access-Control-Allow-Credentials' 'true' always;"
echo "    add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;"
echo "    add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization, X-Requested-With' always;"
echo "    add_header 'Access-Control-Max-Age' '86400' always;"
echo ""
echo "    # Handle preflight OPTIONS requests"
echo "    if (\$request_method = 'OPTIONS') {"
echo "        add_header 'Access-Control-Allow-Origin' \$cors_origin always;"
echo "        add_header 'Access-Control-Allow-Credentials' 'true' always;"
echo "        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;"
echo "        add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization, X-Requested-With' always;"
echo "        add_header 'Access-Control-Max-Age' '86400' always;"
echo "        add_header 'Content-Type' 'text/plain charset=UTF-8';"
echo "        add_header 'Content-Length' '0';"
echo "        return 204;"
echo "    }"
echo "}"
echo ""

echo "Step 4: Test the Nginx configuration"
echo "----------------------------------------"
echo "nginx -t"
echo ""

echo "Step 5: Reload Nginx if the test passes"
echo "----------------------------------------"
echo "systemctl reload nginx"
echo ""

echo "Step 6: Verify the changes"
echo "----------------------------------------"
echo "Run these commands to verify the changes:"
echo ""
echo "curl -sSI -H 'Origin: https://beta-workforcedemocracyproject.netlify.app' \\"
echo "  https://api-beta.workforcedemocracyproject.org/health | grep -i '^access-control-'"
echo ""
echo "curl -sSI https://api-beta.workforcedemocracyproject.org | head -n1"
echo ""
echo "curl -sL https://api-beta.workforcedemocracyproject.org | head -n5"
echo ""

echo "Step 7: Document the changes"
echo "----------------------------------------"
echo "Add an entry to /srv/wdp/shared/changes.log with the results of the verification"
echo "Update ops/COORDINATION.md with the change details"
echo ""
echo "=== End of Instructions ==="